#mybatis.mapper.base.package: com.bogle.erp.repository
#mybatis.aliases.package: com.bogle.erp.entity

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/erp
        username: root
        password:
        initialSize: 0
        maxActive: 20
        minIdle: 0
        maxWait: 60000
        validationQuery: SELECT 1
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: stat
    mybatis:
        aliases: com.bogle.erp.entity
        mapper: com.bogle.erp.repository

logging:
    file: /logs/erp.log